application:
  domain: http://localhost:${server.port}/

server:
  port: 8080

security:
  oauth2:
    client:
      scope: password
      client-id: burls-client
      client-secret: burls-client-secret